<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \app\models\query\ProductQuery;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property string $name
 * @property double $price
 * @property integer $status
 *
 * @property \app\models\OrderItem[] $orderItems
 */
abstract class Product extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['price'], 'number'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
//    public function attributeLabels()
//    {
//        return ArrayHelper::merge(parent::attributeLabels(), [
//            'id' => Yii::t('models', 'ID'),
//            'name' => Yii::t('models', 'Name'),
//            'price' => Yii::t('models', 'Price'),
//            'status' => Yii::t('models', 'Status'),
//        ]);
//    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderItems()
    {
        return $this->hasMany(\app\models\OrderItem::class, ['product_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(static::class);
    }
}
