<?php

namespace app\models\form;

use app\models\Product;

class ProductForm extends Product
{
    public function rules()
    {
        return array_merge(parent::rules(), [
            ["name", "required"]
        ]); // TODO: Change the autogenerated stub
    }
}
